name: travel_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  riverpod: ^2.3.6
  getwidget: ^3.1.1
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-Light.ttf
        - asset: assets/Montserrat/Montserrat-Regular.ttf
        - asset: assets/Montserrat/Montserrat-Bold.ttf
  assets:
    - assets/data.json
